default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: dummyapp
  password:

development:
  <<: *default
  database: dummyapp_development

test:
  <<: *default
  database: dummyapp_test

production:
  <<: *default
  database: dummyapp_production

